USE
[master]
GO

/****** Object:  Database [LessonTwoDb]    Script Date: 27.07.2025 10:06:47 ******/
CREATE
DATABASE [LessonTwoDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LessonTwoDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\LessonTwoDb.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 15%)
 LOG ON 
( NAME = N'LessonTwoDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\LessonTwoDb_log.ldf' , SIZE = 10240KB , MAXSIZE = 61440KB , FILEGROWTH = 5120KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LessonTwoDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER
DATABASE [LessonTwoDb] SET ANSI_NULL_DEFAULT OFF
GO

ALTER
DATABASE [LessonTwoDb] SET ANSI_NULLS OFF
GO

ALTER
DATABASE [LessonTwoDb] SET ANSI_PADDING OFF
GO

ALTER
DATABASE [LessonTwoDb] SET ANSI_WARNINGS OFF
GO

ALTER
DATABASE [LessonTwoDb] SET ARITHABORT OFF
GO

ALTER
DATABASE [LessonTwoDb] SET AUTO_CLOSE OFF
GO

ALTER
DATABASE [LessonTwoDb] SET AUTO_SHRINK OFF
GO

ALTER
DATABASE [LessonTwoDb] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER
DATABASE [LessonTwoDb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER
DATABASE [LessonTwoDb] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER
DATABASE [LessonTwoDb] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER
DATABASE [LessonTwoDb] SET NUMERIC_ROUNDABORT OFF
GO

ALTER
DATABASE [LessonTwoDb] SET QUOTED_IDENTIFIER OFF
GO

ALTER
DATABASE [LessonTwoDb] SET RECURSIVE_TRIGGERS OFF
GO

ALTER
DATABASE [LessonTwoDb] SET  DISABLE_BROKER
GO

ALTER
DATABASE [LessonTwoDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER
DATABASE [LessonTwoDb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER
DATABASE [LessonTwoDb] SET TRUSTWORTHY OFF
GO

ALTER
DATABASE [LessonTwoDb] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER
DATABASE [LessonTwoDb] SET PARAMETERIZATION SIMPLE
GO

ALTER
DATABASE [LessonTwoDb] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER
DATABASE [LessonTwoDb] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER
DATABASE [LessonTwoDb] SET RECOVERY SIMPLE
GO

ALTER
DATABASE [LessonTwoDb] SET  MULTI_USER
GO

ALTER
DATABASE [LessonTwoDb] SET PAGE_VERIFY CHECKSUM
GO

ALTER
DATABASE [LessonTwoDb] SET DB_CHAINING OFF
GO

ALTER
DATABASE [LessonTwoDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER
DATABASE [LessonTwoDb] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER
DATABASE [LessonTwoDb] SET DELAYED_DURABILITY = DISABLED
GO

ALTER
DATABASE [LessonTwoDb] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER
DATABASE [LessonTwoDb] SET QUERY_STORE = ON
GO

ALTER
DATABASE [LessonTwoDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER
DATABASE [LessonTwoDb] SET  READ_WRITE
GO

